import {REGIMES,DAY_TYPES,newRoster,resetCells,datesOf,cellOf,shiftMinutes,auditRoster,validateRosters,addDate,fillRoster,copyNextRoster} from './roster.js';
import { tx } from './i18n.js';
import {SOLVER} from './solver.js';
import {scenarioKey} from './scenarios.js';

const time=n=>(n>=1440?'次日':'')+String(Math.floor(n%1440/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
const segments=s=>s.segments.map(([a,b])=>time(a)+'-'+time(b)).join(',');
function parseSegments(value){return value.split(',').map(v=>v.trim().split('-').map(t=>{const m=/^(次日)?(\d{2}):(\d{2})$/.exec(t.trim());if(!m||+m[2]>23||+m[3]>59)throw new Error('時段格式：08:00-12:00,13:00-17:00；跨夜請寫次日');return (m[1]?1440:0)+Number(m[2])*60+Number(m[3]);}));}

export function rosterUI({state,ui,esc,uid,canEdit,canMaster,open,close,syncInputs,commit,toast,today,clearUndo,jwt}){
  const btn=(act,label,id='',attrs='')=>'<button class="btn" data-act="'+act+'" data-id="'+esc(id)+'" '+attrs+'>'+label+'</button>';
  const field=(k,label,v,type='text')=>'<div class="field"><label for="rs-'+k+'">'+label+'</label><input id="rs-'+k+'" class="inp" type="'+type+'" data-bind="'+k+'" value="'+esc(v??'')+'"></div>';
  const select=(k,label,opts,v)=>'<div class="field"><label for="rs-'+k+'">'+label+'</label><select class="inp" id="rs-'+k+'" data-bind="'+k+'">'+opts.map(([id,t])=>'<option value="'+esc(id)+'" '+(String(id)===String(v)?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></div>';
  const periods=()=>state().staffRosters||[];
  const current=id=>periods().find(p=>p.id===id);
  const preview=(candidate,result,origin=null)=>{validateRosters({...state(),staffRosters:periods().filter(p=>p.id!==candidate.id).concat(candidate)});open({t:'roster-preview',candidate,result,origin,base:scenarioKey(state()),version:state().version});};
  const save=p=>{const S=state(),next=periods().filter(x=>x.id!==p.id).concat(p);validateRosters({...S,staffRosters:next});S.staffRosters=next;clearUndo();commit({kind:'edit',title:'更新輪班草稿 '+p.name,lines:[]});};
  const safe=f=>(a)=>{if(!canEdit())return;try{f(a);}catch(e){toast(e.message);}};
  const warnings=a=>a.errors.map(e=>'<div class="issue">'+esc(state().employees.find(x=>x.id===e.emp)?.name||'制度')+' '+esc(e.date||'')+'：'+esc(e.message)+'</div>').join('')+a.warnings.map(w=>'<div class="hint">'+esc(w)+'</div>').join('');
  const matrix=p=>{const ds=datesOf(p),a=auditRoster(p,state());return '<div class="roster-scroll"><table class="roster-grid"><thead><tr><th>員工／可用班別</th>'+ds.map(d=>'<th>'+d.slice(5)+'<br>'+['日','一','二','三','四','五','六'][new Date(d+'T00:00:00Z').getUTCDay()]+'</th>').join('')+'<th>已排時數</th></tr></thead><tbody>'+p.employees.map(e=>{const emp=state().employees.find(x=>x.id===e.emp);return '<tr><th>'+btn('rs-available',esc(emp.name),e.emp,'data-period="'+esc(p.id)+'"')+'<small>'+e.shiftIds.map(id=>esc(p.shifts.find(s=>s.id===id)?.name)).join('、')+'</small></th>'+ds.map(d=>{const c=cellOf(p,e.emp,d),s=p.shifts.find(s=>s.id===c.shiftId),pos=p.positions.find(x=>x.id===c.positionId),bad=a.errors.some(x=>x.emp===e.emp&&(!x.date||x.date===d));return '<td class="rs-'+c.type+(bad?' rs-error':'')+'">'+btn('rs-cell',(s?esc(s.name)+'<small>'+esc(pos?.name||'未選崗位')+'</small>':DAY_TYPES[c.type]+(c.type==='work'?'<small>未排班</small>':''))+(c.pin?' 📌':''),e.emp,'data-period="'+esc(p.id)+'" data-date="'+d+'" aria-label="'+esc(emp.name+' '+d+' '+(s?.name||DAY_TYPES[c.type]))+'"')+'</td>';}).join('')+'<td>'+a.totals.find(t=>t.emp===e.emp).minutes/60+' h</td></tr>';}).join('')+'</tbody></table></div>';};
  const shortages=(p,a)=>'<h4>崗位／產線需求與產能</h4>'+a.shortages.map(d=>'<div class="rline '+(d.missingPeople||d.missingQty?'issue':'')+'">'+d.date+' '+esc(p.shifts.find(s=>s.id===d.shiftId).name)+' · '+esc(p.positions.find(x=>x.id===d.positionId).name)+'：'+d.count+'/'+d.people+' 人；'+(d.capacity===null?'產能待確認':d.capacity.toFixed(1)+'/'+d.target+' 件')+(d.missingPeople?' · 缺 '+d.missingPeople+' 人':'')+(d.missingQty?' · 缺 '+d.missingQty.toFixed(1)+' 件':'')+'</div>').join('');
  const modals={
    rosters(){return {title:'輪班管理 · Excel 式班表',body:'<div class="hint">輪班表管理員工出勤時段；產線工作方塊另行管理。所有班表目前均為草稿，不是正式出勤或完整合法認證。</div>'+periods().map(p=>btn('rs-open',esc(p.name)+' · '+REGIMES[p.regime].name,p.id)).join('')+(!periods().length?'<div class="empty">尚無輪班草稿。建立後先核定班別、崗位資格與需求，再自動試排。</div>':''),foot:(canEdit()?btn('rs-new','＋建立週期草稿'):'')+btn('close',tx('關閉'))};},
    'roster-new'(m){m.draft||={name:'輪班草稿',start:today(),anchor:today(),factory:ui.factory==='all'?1:ui.factory,regime:'fixed',eligibilityRef:'',consentRef:'',rotationConsentRef:''};const d=m.draft;return {title:'建立輪班草稿',body:field('name','班表名稱',d.name)+field('start','完整週期起日',d.start,'date')+field('anchor','連續週期基準日（不能逐月重設）',d.anchor,'date')+select('factory','主要廠別',[[1,'1 廠'],[2,'2 廠']],d.factory)+select('regime','工時制度',Object.entries(REGIMES).map(([k,v])=>[k,v.name]),d.regime)+field('eligibilityRef','變形工時適用指定行業依據（固定班可空白）',d.eligibilityRef)+field('consentRef','工會／勞資會議同意紀錄（非核准證明）',d.consentRef)+field('rotationConsentRef','同週換班的勞工同意紀錄（可空白）',d.rotationConsentRef)+'<div class="hint">預設週一至週五工作、週六休息、週日例假，與目前工廠開工日不同，請自行核定。製造業不能直接假定可採四週制度。日班預設 08–12、13–17，可自行修改。</div>',foot:btn('close',tx('取消'))+btn('rs-create','建立草稿')};},
    'roster-sheet'(m){const p=current(m.id);if(!p)return null;const a=auditRoster(p,state());return {title:esc(p.name)+' · '+REGIMES[p.regime].name+' · 草稿',body:'<div class="hint">'+p.start+' ～ '+datesOf(p).at(-1)+'；基準 '+p.anchor+'。點班格更換班別／崗位／休假；點員工設定可用星期。📌 固定班格試排不移動。工作日未排班仍保留原日別，不能用來抵充例假。</div>'+matrix(p)+'<h4>崗位資格／產能設定</h4>'+p.positions.map(pos=>btn('rs-position-edit',esc(pos.name)+' · '+(pos.rate??'待確認')+' 件／人時',pos.id,'data-period="'+esc(p.id)+'"')).join('')+shortages(p,a)+'<details><summary>工時檢核：'+a.errors.length+' 項衝突／'+a.warnings.length+' 項待確認</summary>'+warnings(a)+'</details>',foot:btn('rosters','清單')+(canEdit()?btn('rs-shift','＋班別',p.id)+btn('rs-position','＋崗位／產能',p.id)+btn('rs-member','＋支援員工',p.id)+btn('rs-demand','＋需求',p.id)+btn('rs-fill','批次填班',p.id)+btn('rs-next','複製下一週期',p.id)+btn('rs-auto','OR-Tools 自動試排',p.id):'')+btn('close',tx('關閉'))};},
    'roster-cell'(m){const p=current(m.period),c=cellOf(p,m.emp,m.date);m.draft||=structuredClone(c);const d=m.draft;return {title:esc(state().employees.find(x=>x.id===m.emp).name)+' · '+m.date,body:select('type','日期性質',Object.entries(DAY_TYPES),d.type)+select('shiftId','班別',[['','未排班'],...p.shifts.map(s=>[s.id,s.name+' · '+segments(s)])],d.shiftId)+select('positionId','工作崗位',[['','未選擇'],...p.positions.map(s=>[s.id,s.name])],d.positionId)+select('pin','固定此班格',[[0,'否'],[1,'是']],d.pin?1:0)+'<div class="hint">只改輪班草稿，不移動現有產線工作。例假、休息日、請假與假日目前不支援安排出勤。</div>',foot:btn('rs-back','取消',p.id)+(canEdit()?btn('rs-cell-save','暫存班格',p.id):'')};},
    'roster-shift'(m){const p=current(m.id);m.draft||={shiftId:p.shifts[0].id,name:p.shifts[0].name,segments:segments(p.shifts[0])};return {title:'新增／編輯班別',body:select('shiftId','選擇班別',[['','新增班別'],...p.shifts.map(s=>[s.id,s.name])],m.draft.shiftId)+btn('rs-load-shift','載入選擇',p.id)+field('name','班別名稱',m.draft.name)+field('segments','實際工作時段（逗號分段，扣除休息）',m.draft.segments)+'<div class="hint">例如 08:00-12:00,13:00-17:00；夜班：22:00-次日02:00,次日02:30-次日06:30。班別修改會重新檢核所有班格；草稿仍可保留衝突供修正。</div>',foot:btn('rs-back','取消',p.id)+btn('rs-shift-save','暫存班別',p.id)};},
    'roster-position'(m){const p=current(m.id);m.draft||={id:uid(),name:'',rate:'',employeeIds:[]};const d=m.draft;return {title:'工作崗位／確認資格',body:'<div class="hint">可填人工工作、設備工位或部門名稱。不從 1023 欄名猜測員工資格及產能；每人每小時產能僅作人力需求估算，未計設備瓶頸、合做或換模。</div>'+field('name','工作崗位／工作內容',d.name)+field('rate','每人每小時產能（可空白，不猜測）',d.rate,'number')+'<div class="field">確認可上此崗位的員工<br>'+p.employees.map(e=>btn('rs-qualified',esc(state().employees.find(x=>x.id===e.emp).name),e.emp,'aria-pressed="'+d.employeeIds.includes(e.emp)+'"')).join('')+'</div>',foot:btn('rs-back','取消',p.id)+btn('rs-position-save','暫存崗位',p.id)};},
    'roster-available'(m){const p=current(m.period);m.draft||=structuredClone(p.employees.find(e=>e.emp===m.emp));const d=m.draft;return {title:'員工可用時段／跨廠借調',body:'<div class="hint">本週期已納入此員工；原廠別與員工資料不變。請假由員工名冊讀取。未確認 1023 身分者不自動排入。</div><h4>可上班別</h4>'+p.shifts.map(s=>btn('rs-allow-shift',esc(s.name),s.id,'aria-pressed="'+d.shiftIds.includes(s.id)+'"')).join('')+'<h4>可上班星期</h4>'+[0,1,2,3,4,5,6].map(n=>btn('rs-allow-day','週'+['日','一','二','三','四','五','六'][n],String(n),'aria-pressed="'+d.weekdays.includes(n)+'"')).join(''),foot:btn('rs-back','取消',p.id)+btn('rs-available-save','暫存可用時段',p.id)};},
    'roster-demand'(m){const p=current(m.id);m.draft||={date:p.start,shiftId:p.shifts[0].id,positionId:p.positions[0]?.id||'',people:1,target:0,repeat:0};const d=m.draft;return {title:'設定每日崗位需求',body:field('date','需求日期',d.date,'date')+select('shiftId','班別',p.shifts.map(x=>[x.id,x.name]),d.shiftId)+select('positionId','崗位',p.positions.map(x=>[x.id,x.name]),d.positionId)+field('people','至少需要幾人',d.people,'number')+field('target','此班別產量目標（0 = 只檢查人數）',d.target,'number')+select('repeat','套用範圍',[[0,'只限此日'],[1,'整個週期週一至週五']],d.repeat)+'<div class="hint">同日期＋班別＋崗位會取代原需求；不改正式工單。產量目標需要使用者確認產能。</div>',foot:btn('rs-back','取消',p.id)+btn('rs-demand-save','暫存需求',p.id)};},
    'roster-fill'(m){const p=current(m.id);m.draft||={emp:'all',from:p.start,to:datesOf(p).at(-1),type:'work',shiftId:p.shifts[0].id,positionId:p.positions[0]?.id||''};const d=m.draft;return {title:'批次填班 · 先預覽',body:select('emp','員工範圍',[['all','本班表所有員工'],...p.employees.map(e=>[e.emp,state().employees.find(x=>x.id===e.emp).name])],d.emp)+field('from','起日',d.from,'date')+field('to','迄日',d.to,'date')+select('type','填入日別',Object.entries(DAY_TYPES),d.type)+select('shiftId','工作日班別',p.shifts.map(s=>[s.id,s.name]),d.shiftId)+select('positionId','工作崗位',[['','未指定'],...p.positions.map(s=>[s.id,s.name])],d.positionId)+'<div class="hint">填工作日只處理原工作格，不覆蓋休假／請假；固定格一律保留。填例假／休息日會清除该格原班別，預覽確認才存入。</div>',foot:btn('rs-back','取消',p.id)+btn('rs-fill-preview','預覽填充',p.id)};},
    'roster-member'(m){const p=current(m.id);m.draft||={emp:''};return {title:'加入員工 · 跨廠／跨部門支援',body:select('emp','選擇既有名冊人員',[['','請選擇'],...state().employees.filter(e=>!p.employees.some(x=>x.emp===e.id)).map(e=>[e.id,e.name+' · '+(e.factory||1)+' 廠'])],m.draft.emp)+'<div class="hint">加入後還需設定可上班別與確認崗位資格；不修改原部門或廠別。同人重疊週期會被拒絕。</div>',foot:btn('rs-back','取消',p.id)+btn('rs-member-save','加入此草稿',p.id)};},
    'roster-preview'(m){const a=auditRoster(m.candidate,state());return {title:esc(m.result.engine)+' · 輪班預覽',body:'<div class="okbox">'+esc(m.result.engine)+' · '+esc(m.result.status)+(m.result.seconds!==undefined?' · '+m.result.seconds+' 秒':'')+'</div><div class="hint">確認前草稿不改動；確認後仍不移動產線工作。缺額可保留，不能視為需求已滿足。</div>'+matrix(m.candidate)+shortages(m.candidate,a)+warnings(a),foot:btn('rs-back','取消',m.origin||m.candidate.id)+(canEdit()?btn('rs-apply','確認存入輪班草稿',m.candidate.id,a.errors.length?'disabled':''):'')};}
  };
  const actions={
    rosters:()=>open({t:'rosters'}),'rs-open':a=>open({t:'roster-sheet',id:a.dataset.id}),'rs-back':a=>open({t:'roster-sheet',id:a.dataset.id}),
    'rs-new':safe(()=>open({t:'roster-new'})),
    'rs-create':safe(()=>{syncInputs();const d=ui.modal.draft,p=newRoster(state(),{id:uid(),start:d.start,factory:Number(d.factory)});Object.assign(p,d,{factory:Number(d.factory)});resetCells(p,state());save(p);open({t:'roster-sheet',id:p.id});}),
    'rs-cell':a=>open({t:'roster-cell',period:a.dataset.period,emp:a.dataset.id,date:a.dataset.date}),
    'rs-cell-save':safe(a=>{syncInputs();const m=ui.modal,p=structuredClone(current(a.dataset.id)),d={...m.draft,shiftId:m.draft.shiftId||null,positionId:m.draft.positionId||null,pin:!!Number(m.draft.pin)};if(d.type!=='work'){d.shiftId=null;d.positionId=null;}p.cells=p.cells.map(c=>c.emp===d.emp&&c.date===d.date?d:c);save(p);open({t:'roster-sheet',id:p.id});}),
    'rs-shift':safe(a=>open({t:'roster-shift',id:a.dataset.id})),
    'rs-load-shift':safe(a=>{syncInputs();const m=ui.modal,s=current(a.dataset.id).shifts.find(s=>s.id===m.draft.shiftId);if(s)m.draft={shiftId:s.id,name:s.name,segments:segments(s)};else m.draft={shiftId:'',name:'',segments:''};open(m);}),
    'rs-shift-save':safe(a=>{syncInputs();const d=ui.modal.draft,p=structuredClone(current(a.dataset.id)),s={id:d.shiftId||uid(),name:d.name.trim(),segments:parseSegments(d.segments)};p.shifts=p.shifts.filter(x=>x.id!==s.id).concat(s);save(p);open({t:'roster-sheet',id:p.id});}),
    'rs-position':safe(a=>open({t:'roster-position',id:a.dataset.id})),
    'rs-position-edit':safe(a=>open({t:'roster-position',id:a.dataset.period,draft:structuredClone(current(a.dataset.period).positions.find(x=>x.id===a.dataset.id))})),
    'rs-fill':safe(a=>open({t:'roster-fill',id:a.dataset.id})),
    'rs-fill-preview':safe(a=>{syncInputs();const {candidate,changed,skipped}=fillRoster(current(a.dataset.id),state(),ui.modal.draft);preview(candidate,{engine:'手動批次填充',status:'修改 '+changed+' 格；保留 '+skipped+' 格'});}),
    'rs-next':safe(a=>{const p=current(a.dataset.id);preview(copyNextRoster(p,state(),uid()),{engine:'複製下一週期',status:'保留連續週期錨點；解除固定並重新帶入請假'},p.id);}),
    'rs-member':safe(a=>open({t:'roster-member',id:a.dataset.id})),
    'rs-member-save':safe(a=>{syncInputs();const p=structuredClone(current(a.dataset.id)),emp=ui.modal.draft.emp;if(!state().employees.some(e=>e.id===emp))throw new Error('請選擇既有員工');const temp={...p,employees:[{emp,shiftIds:[],weekdays:[1,2,3,4,5]}]};resetCells(temp,state());p.employees.push(temp.employees[0]);p.cells.push(...temp.cells);save(p);open({t:'roster-sheet',id:p.id});}),
    'rs-qualified':safe(a=>{syncInputs();const m=ui.modal,d=m.draft;d.employeeIds=d.employeeIds.includes(a.dataset.id)?d.employeeIds.filter(x=>x!==a.dataset.id):d.employeeIds.concat(a.dataset.id);open(m);}),
    'rs-position-save':safe(a=>{syncInputs();const p=structuredClone(current(a.dataset.id)),d=ui.modal.draft,rate=document.getElementById('rs-rate').value;p.positions=p.positions.filter(x=>x.id!==d.id).concat({...d,name:d.name.trim(),rate:rate===''?null:Number(rate)});save(p);open({t:'roster-sheet',id:p.id});}),
    'rs-available':a=>open({t:'roster-available',period:a.dataset.period,emp:a.dataset.id}),
    'rs-allow-shift':safe(a=>{const m=ui.modal,d=m.draft;d.shiftIds=d.shiftIds.includes(a.dataset.id)?d.shiftIds.filter(x=>x!==a.dataset.id):d.shiftIds.concat(a.dataset.id);open(m);}),
    'rs-allow-day':safe(a=>{const m=ui.modal,d=m.draft,n=Number(a.dataset.id);d.weekdays=d.weekdays.includes(n)?d.weekdays.filter(x=>x!==n):d.weekdays.concat(n);open(m);}),
    'rs-available-save':safe(a=>{const p=structuredClone(current(a.dataset.id)),d=ui.modal.draft;p.employees=p.employees.map(e=>e.emp===d.emp?d:e);save(p);open({t:'roster-sheet',id:p.id});}),
    'rs-demand':safe(a=>{if(!current(a.dataset.id).positions.length)throw new Error('請先新增崗位及確認員工资格');open({t:'roster-demand',id:a.dataset.id});}),
    'rs-demand-save':safe(a=>{syncInputs();const d=ui.modal.draft,p=structuredClone(current(a.dataset.id)),ds=Number(d.repeat)?datesOf(p).filter(date=>[1,2,3,4,5].includes(new Date(date+'T00:00:00Z').getUTCDay())):[d.date];for(const date of ds){const row={date,shiftId:d.shiftId,positionId:d.positionId,people:Number(d.people),target:Number(d.target)};p.demands=p.demands.filter(x=>!(x.date===date&&x.shiftId===row.shiftId&&x.positionId===row.positionId)).concat(row);}save(p);open({t:'roster-sheet',id:p.id});}),
    'rs-auto':async a=>{if(!canEdit())return;const p=structuredClone(current(a.dataset.id)),base=scenarioKey(state()),version=state().version,modal=ui.modal;try{
      if(state().setupPending||p.employees.some(x=>{const e=state().employees.find(e=>e.id===x.emp);return e.reviewStatus&&e.reviewStatus!=='confirmed';}))throw new Error('請先核定員工身分與名冊');
      const previous=periods().find(q=>q.id!==p.id&&addDate(q.start,REGIMES[q.regime].days)===p.start),request={roster:p,workers:state().employees.filter(e=>p.employees.some(x=>x.emp===e.id)),occupied:[...(state().blocks||[]),...(state().workAssignments||[])].filter(b=>p.employees.some(e=>e.emp===b.emp)&&datesOf(p).includes(b.date)).map(b=>({emp:b.emp,date:b.date,s:b.s,e:b.e})),previous:previous?.cells.filter(c=>c.date>=addDate(p.start,-6))||[],previousShifts:previous?.shifts||[],time_limit:3};
      a.disabled=true;toast('正在以 OR-Tools 試排輪班…');const result=await SOLVER.roster(request,jwt());if(ui.modal!==modal)return;if(base!==scenarioKey(state())||version!==state().version)throw new Error('資料已更新，請重新試排');if(!result.cells)throw new Error('未找到可行班表：'+result.status+'；草稿未改動');
      const candidate={...p,cells:result.cells};validateRosters({...state(),staffRosters:periods().filter(x=>x.id!==p.id).concat(candidate)});open({t:'roster-preview',candidate,result,base,version});
    }catch(e){toast(e.message);}finally{a.disabled=false;}},
    'rs-apply':safe(()=>{const m=ui.modal;if(m.t!=='roster-preview'||m.base!==scenarioKey(state())||m.version!==state().version)throw new Error('資料已更新，請重新試排');if(auditRoster(m.candidate,state()).errors.length)throw new Error('檢核仍有衝突，不可套用試排');save(m.candidate);open({t:'roster-sheet',id:m.candidate.id});})
  };
  return {modals,actions};
}
