import {transferOrders,transferSummary,batchTotals,FLOW_ACTIONS,validateTransfers,appendFlow,transferPlanWarnings} from './transfers.js';
import { tx } from './i18n.js';

export function transferUI({state,ui,esc,uid,canEdit,open,close,syncInputs,commit,toast,today,clearUndo}){
  const btn=(act,label,id='',extra='')=>'<button class="btn" data-act="'+act+'" data-id="'+esc(id)+'" '+extra+'>'+label+'</button>';
  const field=(key,label,value,type='text',disabled=false)=>'<div class="field"><label for="tf-'+key+'">'+label+'</label><input class="inp" id="tf-'+key+'" data-bind="'+key+'" type="'+type+'" value="'+esc(value??'')+'" '+(disabled?'disabled':'')+'></div>';
  const select=(key,label,values,value,disabled=false)=>'<div class="field"><label for="tf-'+key+'">'+label+'</label><select class="inp" id="tf-'+key+'" data-bind="'+key+'" '+(disabled?'disabled':'')+'>'+values.map(([v,t])=>'<option value="'+v+'" '+(String(v)===String(value)?'selected':'')+'>'+t+'</option>').join('')+'</select></div>';
  const warnings=items=>items.map(t=>'<div class="issue">'+esc(t)+'</div>').join('');
  const current=id=>transferOrders(state()).find(o=>o.id===id);
  const commitOrders=(orders,title)=>{const S=state(),candidate={...S,transferOrders:orders};validateTransfers(candidate,{before:S});S.transferOrders=orders;clearUndo();close();commit({kind:'edit',title,lines:[]});};
  const normalizedDraft=()=>{syncInputs();const D=structuredClone(ui.modal.draft);for(const k of ['notified','expectedSend','due','urgentDue'])if(k in D)D[k]=document.getElementById('tf-'+k)?.value||null;if('totalQty' in D)D.totalQty=document.getElementById('tf-totalQty')?.value===''?null:Number(D.totalQty);return D;};
  const safe=f=>()=>{if(!canEdit())return;try{f();}catch(e){toast(e.message);}};
  const modals={
    'transfer-board'(){const S=state(),rows=transferOrders(S).filter(o=>ui.factory==='all'||[o.fromFactory,o.toFactory,o.returnFactory].includes(ui.factory)).sort((a,b)=>String(a.notified||a.due||'9999').localeCompare(String(b.notified||b.due||'9999')));
      const fmt=d=>d&&/^\d{4}-\d{2}-\d{2}$/.test(d)?d.slice(5).replace('-','/'):'—';
      const td=v=>v===null||v===undefined||v===''?'<span class="mute">—</span>':esc(String(v));
      return {title:'跨廠加工通知總表',body:'<div class="hint">對照現場通知表的欄位：通知日期＝何時通知 2 廠、加工編號＝加工單號、全部可給數＝總需求量、何時給2廠＝預計交料日、急用＝急用數量、要求回1廠＝回廠期限。點一列看完整加工單與批次流轉。</div>'+
        '<div class="tf-board"><table><thead><tr><th>'+tx('通知日期')+'</th><th>'+tx('加工編號')+'</th><th>'+tx('全部可給數')+'</th><th>'+tx('何時給2廠時間')+'</th><th>'+tx('急用')+'</th><th>'+tx('要求回1廠時間')+'</th></tr></thead><tbody>'+
        (rows.map(o=>{const t=transferSummary(o,today());return '<tr class="tf-row" data-act="tf-detail" data-id="'+esc(o.id)+'"><td>'+td(fmt(o.notified))+'</td><td><b>'+esc(o.code)+'</b><small>'+esc(o.itemCode)+'</small></td><td>'+td(o.totalQty)+'</td><td>'+td(fmt(o.expectedSend))+'</td><td>'+(o.urgentQty?esc(o.urgentQty)+(t.urgentMissing>0?'<small class="tf-miss">缺 '+t.urgentMissing+'</small>':''):'<span class="mute">—</span>')+'</td><td>'+td(fmt(o.due))+'</td></tr>';}).join('')||'<tr><td colspan="6"><div class="empty">'+tx('目前沒有跨廠加工通知')+'</div></td></tr>')+
        '</tbody></table></div>',foot:btn('transfers','完整加工單管理')+btn('close',tx('關閉'))};},
    transfers(){const S=state(),rows=transferOrders(S).filter(o=>ui.factory==='all'||[o.fromFactory,o.toFactory,o.returnFactory].includes(ui.factory)).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));
      return {title:'跨廠加工',body:'<div class="hint">預計交料不等於已到料。實際點收才會增加可加工／可回廠使用量；流轉紀錄不等於排班已完成。</div>'+rows.map(o=>{const t=transferSummary(o,today());return '<div class="field transfer-card">'+btn('tf-detail',esc(o.code)+' · '+esc(o.itemCode),o.id)+'<div>'+o.fromFactory+' 廠 → '+o.toFactory+' 廠 → '+o.returnFactory+' 廠 · '+t.status+'</div><div>總需求 '+(o.totalQty??'待確認')+' · 到料 '+t.receive+' · 完成 '+t.complete+' · 回廠合格 '+t.accept+'</div><div>回廠期限 '+esc(o.due||'待確認')+' · 急用缺口 '+t.urgentMissing+'</div>'+warnings(t.warnings)+'</div>';}).join('')+(!rows.length?'<div class="empty">'+tx('尚未建立跨廠加工單；不會自動匯入貼上的歷史資料。')+'</div>':''),foot:(canEdit()?btn('tf-new','＋新增加工單'):'')+btn('close',tx('關閉'))};},
    'transfer-detail'(m){const S=state(),o=current(m.id);if(!o)return null;const t=transferSummary(o,today());
      return {title:'加工單 '+esc(o.code),body:'<dl class="kv"><dt>'+tx('加工品號')+'</dt><dd>'+esc(o.itemCode)+'</dd><dt>'+tx('廠別')+'</dt><dd>'+o.fromFactory+' → '+o.toFactory+' → '+o.returnFactory+'</dd><dt>'+tx('加工內容')+'</dt><dd>'+o.workIds.map(id=>esc(S.workContents.find(w=>w.id===id)?.name||'待確認')).join('、')+'</dd><dt>'+tx('總量／急用')+'</dt><dd>'+(o.totalQty??'待確認')+'／'+o.urgentQty+' 件</dd><dt>'+tx('預計交料')+'</dt><dd>'+esc(o.expectedSend||'待確認')+'</dd><dt>'+tx('回廠／急用期限')+'</dt><dd>'+esc(o.due||'待確認')+'／'+esc(o.urgentDue||'未指定')+'</dd><dt>'+tx('狀態')+'</dt><dd>'+t.status+'</dd><dt>'+tx('備註')+'</dt><dd>'+esc(o.note)+'</dd></dl>'+warnings(t.warnings)+
        o.batches.map(b=>{const n=batchTotals(o,b),linked=(S.workAssignments||[]).filter(a=>a.transferBatchId===b.id);return '<section class="field transfer-card"><h4>'+esc(b.code)+' · 計畫 '+b.plannedQty+' 件</h4><div>交出 '+n.send+' → 點收 '+n.receive+' → 完成良品 '+n.complete+' → 送回 '+n.return+' → 點收合格 '+n.accept+'</div><div>加工不良 '+n.scrap+' · 回廠點收差異 '+n.rejected+'</div>'+(canEdit()&&o.status==='active'?btn('tf-flow','＋登記流轉',b.id)+btn('tf-plan','＋連結人工／設備排班',b.id):'')+
          '<h4>'+tx('相關排班')+'</h4>'+linked.map(a=>'<div>'+btn('general-edit',esc(S.employees.find(e=>e.id===a.emp)?.name||'?')+' · '+esc(S.workContents.find(w=>w.id===a.workId)?.name||'?')+' · '+a.qty+' 件',a.id)+'<div>'+esc(a.date)+' '+String(Math.floor(a.s/60)).padStart(2,'0')+':'+String(a.s%60).padStart(2,'0')+' · '+(a.transferStage==='return'?'回廠後工作':'加工工作')+'</div>'+warnings(transferPlanWarnings(S,a))+'</div>').join('')+(!linked.length?'<div class="hint">'+tx('尚未連結排班。')+'</div>':'')+
          '<h4>'+tx('批次紀錄')+'</h4>'+o.events.filter(e=>e.batchId===b.id).map(e=>'<div class="rline">'+esc(e.at.replace('T',' '))+' · '+FLOW_ACTIONS[e.action]+' '+e.qty+' 件'+(e.badQty?' · 不良／差異 '+e.badQty+' 件':'')+' '+esc(e.note)+'</div>').join('')+'</section>';}).join(''),foot:btn('transfers','返回清單')+(canEdit()?btn('tf-edit','編輯需求',o.id)+(o.status==='active'?btn('tf-batch','＋新增批次',o.id):''):'')+btn('close',tx('關閉'))};},
    'transfer-edit'(m){m.draft ||= structuredClone(current(m.id)||{id:uid(),code:'XF-'+String(transferOrders(state()).length+1).padStart(3,'0'),itemCode:'',fromFactory:1,toFactory:2,returnFactory:1,totalQty:null,urgentQty:0,notified:today(),expectedSend:null,due:null,urgentDue:null,workIds:[],status:'active',note:'',batches:[],events:[]});const D=m.draft,off=!canEdit();
      return {title:m.id?'編輯跨廠需求':'新增加工單',body:'<div class="hint">工作內容由使用者核定，不從品號猜測工序、模具、產能或年份。空白數量／期限保留待確認。</div>'+field('code','加工單號',D.code,'text',off)+field('itemCode','加工品號／產品識別',D.itemCode,'text',off)+
        ['fromFactory','toFactory','returnFactory'].map((k,i)=>select(k,['來源廠','加工廠','回收廠'][i],[[1,'1 廠'],[2,'2 廠']],D[k],off)).join('')+field('totalQty','總需求數量（可留空）',D.totalQty,'number',off)+field('urgentQty','急用數量（總量的一部分）',D.urgentQty,'number',off)+
        [['notified','通知日期'],['expectedSend','預計交料日期'],['due','要求回廠期限'],['urgentDue','急用期限']].map(([k,t])=>field(k,t,D[k],'date',off)).join('')+
        '<div class="field"><span class="lab">'+tx('加工內容（須屬於加工廠；可新增後再選）')+'</span>'+state().workContents.filter(w=>w.factory===Number(D.toFactory)).map(w=>btn('tf-work',esc(w.name),w.id,'aria-pressed="'+D.workIds.includes(w.id)+'" '+(off?'disabled':''))).join('')+'</div>'+select('status','需求狀態',[['active','啟用'],['paused','暫停'],['cancelled','取消（保留紀錄）']],D.status,off)+field('note','需求備註',D.note,'text',off),foot:btn('close',tx('取消'))+(canEdit()?btn('tf-save','儲存加工需求'):'')};},
    'transfer-batch'(m){m.draft ||= {id:uid(),code:'批次-'+String(current(m.id).batches.length+1),plannedQty:0};return {title:'新增交料批次',body:field('code','批次名稱',m.draft.code)+field('plannedQty','此批次計畫數量',m.draft.plannedQty,'number')+'<div class="hint">'+tx('建立批次不代表已交料。全部批次量不得超過加工單總量。')+'</div>',foot:btn('close',tx('取消'))+btn('tf-batch-save','建立批次')};},
    'transfer-flow'(m){m.draft ||= {id:uid(),batchId:m.batchId,action:'send',at:today()+'T'+new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()),qty:0,badQty:0,note:''};const D=m.draft;return {title:'登記實際批次流轉',body:'<div class="hint">'+tx('每次填本次增加的數量，不是累計數量。紀錄存入後不可刪改；差異請另行記錄處理。')+'</div>'+select('action','流轉動作',Object.entries(FLOW_ACTIONS),D.action)+field('at','實際時間（台灣時間）',D.at,'datetime-local')+field('qty','本次交付／良品數量',D.qty,'number')+field('badQty','本次不良／點收差異（只限加工完成、回廠點收）',D.badQty,'number')+field('note','流轉備註',D.note),foot:btn('close',tx('取消'))+btn('tf-flow-preview','預覽流轉')};},
    'transfer-flow-preview'(m){return {title:'確認流轉紀錄',body:'<div class="okbox">'+FLOW_ACTIONS[m.event.action]+' '+m.event.qty+' 件 · 不良／差異 '+m.event.badQty+' 件<br>'+esc(m.event.at.replace('T',' '))+'</div><div class="hint">'+tx('確認後保存真實流轉，不會自動把人工排班標為完成。')+'</div>',foot:btn('close',tx('取消'))+btn('tf-flow-apply','確認存入流轉')};}
  };
  const actions={
    transfers:()=>open({t:'transfers'}),'tf-new':()=>{if(canEdit())open({t:'transfer-edit'});},'tf-detail':a=>open({t:'transfer-detail',id:a.dataset.id}),'tf-edit':a=>open({t:'transfer-edit',id:a.dataset.id}),
    'tf-work':a=>{if(!canEdit())return;syncInputs();const d=ui.modal.draft;d.workIds=d.workIds.filter(id=>id!==a.dataset.id).concat(d.workIds.includes(a.dataset.id)?[]:[a.dataset.id]);open(ui.modal);},
    'tf-save':safe(()=>{const D=normalizedDraft();D.code=D.code.trim();D.itemCode=D.itemCode.trim();for(const k of ['fromFactory','toFactory','returnFactory'])D[k]=Number(D[k]);commitOrders(transferOrders(state()).filter(o=>o.id!==D.id).concat(D),'更新跨廠加工單 '+D.code);}),
    'tf-batch':a=>{if(canEdit())open({t:'transfer-batch',id:a.dataset.id});},
    'tf-batch-save':safe(()=>{syncInputs();const m=ui.modal,orders=structuredClone(transferOrders(state())),o=orders.find(o=>o.id===m.id);if(o.status!=='active')throw new Error('加工單未啟用');o.batches.push(m.draft);commitOrders(orders,'建立跨廠批次 '+m.draft.code);}),
    'tf-flow':a=>{if(!canEdit())return;const o=transferOrders(state()).find(o=>o.batches.some(b=>b.id===a.dataset.id));open({t:'transfer-flow',id:o.id,batchId:a.dataset.id});},
    'tf-flow-preview':safe(()=>{syncInputs();const m=ui.modal,event=structuredClone(m.draft),now=today()+'T'+new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());if(event.at>now)throw new Error('實際流轉不能填未來時間');appendFlow(state(),m.id,event);open({t:'transfer-flow-preview',id:m.id,event});}),
    'tf-flow-apply':safe(()=>{const m=ui.modal;if(m.t!=='transfer-flow-preview')return;const next=appendFlow(state(),m.id,m.event);commitOrders(transferOrders(next),'登記跨廠 '+FLOW_ACTIONS[m.event.action]);}),
    'tf-plan':a=>{if(!canEdit()||state().setupPending){toast('請先核定名冊與工時再排班');return;}const o=transferOrders(state()).find(o=>o.batches.some(b=>b.id===a.dataset.id)),b=o.batches.find(b=>b.id===a.dataset.id);if(!o.workIds.length){toast('請先在加工需求選擇已核定工作內容');return;}ui.factory=o.toFactory;open({t:'general-edit',draft:{id:uid(),workId:o.workIds[0],emp:'',resourceId:null,date:ui.date,s:480,e:540,qty:b.plannedQty,orderId:null,note:'',transferBatchId:b.id,transferStage:'process'}});}
  };
  return {modals,actions};
}
